#!/usr/bin/env bash
#install nginx on webserver

sudo apt-get install -y nginx

sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
	listen 80 default_server;
	listen [::]:80 default_server

	root /var/www/html;
	www.index.html index.html;

	location / {
		return 200 "Hello World!";
	}

}
EOF

sudo server nginx restart
