#!/usr/bin/env bash
# redirect 

sudo apt update -y

sudo apt install nginx -y

echo "Hello World!" > /var/www/html/index.html

redirect_string="rewrite ^/redirect_me https://www.youtube.com/watch?v=_S7WEVLbQ-Y permanent;"
sudo sed -i "/server_name _;/a $redirect_string" /etc/nginx/sites-available/default

sudo apt install ufw -y

sudo ufw allow 'Nginx HTTP'

sudo service nginx restart
