#!/usr/bin/env bash

# redirect 
apt update -y

apt install nginx -y

echo "Hello World!" > /var/www/html/index.html

echo "server {
    server_name localhost;

    location /redirect_me {
        rewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }
}" > /etc/nginx/sites-available/default

ufw allow 'Nginx HTTP'

service nginx start
