#!/usr/bin/env bash

# redirect 
apt update -y

apt install nginx -y

echo "Hello World!" > /var/www/html/index.html

new_str=$"\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=_S7WEVLbQ-Y;\n\t}"
sed -i '/^}$/i \ '"$new_str" /etc/nginx/sites-available/default

echo "Sorry (Ceci n'est pas une page) Ahahah" > /var/www/html/404.html
err_str=$"\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}"
sed -i '/^}$/i \ '"$err_str" /etc/nginx/sites-available/default

apt install ufw -y

ufw allow 'Nginx HTTP'

# Enable the UFW firewall
ufw enable

service nginx restart

