#!/usr/bin/env bash
#redirect 

apt update -y
apt install nginx -y

# set the localhost default page
echo  "Hello World!" > /var/www/html/index.html

redirect_string="rewrite ^/redirect_me https://www.youtube.com/watch?v=_S7WEVLbQ-Y permanent;"
sudo sed -i "/server_name _;/a $redirect_string" /etc/nginx/sites-available/default

# create a default 404 error page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Corrected line to update Nginx configuration with custom error page
err_str="error_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t};"
sudo sed -i "/listen 80 default_server;/c $err_str" /etc/nginx/sites-available/default

passed_string="location / {"
http_head="location / {\n\tadd_header X-Served-By \$hostname;"
sudo sed -i "s|$passed_string|$http_head|" /etc/nginx/sites-available/default

apt install ufw -y

ufw allow 'Nginx HTTP'

service nginx restart
