#!/usr/bin/env bash
#displays numbers from 1 to 100

display=1

while [ "$display" -lt 100 ]
do
	if [ $((display % 3)) -eq 0 ] && [ $((display % 5)) -eq 0 ]
	then
		echo "FIzzBuzz"
	elif [ $((display % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((display % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo $display
	fi

	((display++))
done
