#!/usr/bin/env bash
#Display Best School 10 times

display=1

while [ $display -le 20 ]
do
	echo "$display"
	case "$display" in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((display++))
done
