#!/usr/bin/env bash
#Display the content of a directory

if test school
then 
	echo "school file exist"
	if test -s school
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if test -f school
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi


