#!/usr/bin/env bash
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

host="/etc/hosts"
tmp="/tmp/hosts.tmp"

cp "$host" "$tmp"

echo "127.0.0.2 localhost" > "$tmp"
echo "8.8.8.8 facebook.com" >> "$tmp"

cp -f "$tmp" "$host"
